version: '3.7'

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rentx
    volumes:
      - ~/dbdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rentx-api
    restart: always
    ports:
      - 8081:8081
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local