version: "3.3"

services:
  database:
    image: postgres
    container_name: database_rentx
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=RENTX
    volumes:
      - pgdata:/data/postgres
      
  app:
    build: .
    container_name: rentx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes: 
  pgdata:
    driver: local